server:
  port: 58080
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://192.168.8.65:3306/sas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: sas
    password: QM7yfgiFu
    driver-class-name: com.mysql.cj.jdbc.Driver
  second:
    url: jdbc:postgresql://47.98.46.0:5432/jinshang
    username: admin_jinshang_dev
    password: admin04131
    driver-class-name: org.postgresql.Driver
  sqlserver:
    url: jdbc:sqlserver://47.111.169.100:1433;DatabaseName=UFTData449729_000005
    username: sa
    password: jinshang9988@#
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

yongyou:
  url:  http://47.111.167.68:8000/api/Report/AccountsReceivable

