server:
  port: 58080
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://192.168.8.65:3306/sas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: sas
    password: QM7yfgiFu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

